rabbitmq:
  enabled: true
  replicaCount: 2

  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 2
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80

  backup:
    enabled: false

  tsc:
    enabled: true

  image:
    tag: 4.2-debian-12-20251212-224016

  hosts:
    management: dev-moti-rabbitmq.apps.gold.devops.gov.bc.ca
    stomp: dev-moti-rabbitmq-stomp.apps.gold.devops.gov.bc.ca

allowedNamespace:
  - name: fb3c60
    environment: dev
