rabbitmq:
  enabled: true
  replicaCount: 2

  tsc:
    enabled: true

  image:
    tag: 4.2-debian-12-20251212-214433

  hosts:
    management: dev-moti-rabbitmq.apps.silver.devops.gov.bc.ca
    stomp: dev-moti-rabbitmq-stomp.apps.silver.devops.gov.bc.ca

allowedNamespace:
  - name: fdf5df
    environment: dev
